config_name: sketch
description: "base config, k=10. Restore weights from <sketch>"

n_layers: 5
k_iters: 10
epochs: 50

dataset_name: modl_dataset
dataset_params:
  dataset_path: '/data/xzc/data/dataset.hdf5'
  sigma: 0.01
val_data: False
batch_size: 1

model_name: base_modl

restore_weights: final #False, best, inter, final
# restore_path: 'workspace/sketch/checkpoints/'
restore_path: 

loss_name: MSE
score_names: ['PSNR', 'SSIM']
optim_name: Adam
optim_params:
  lr: 0.001
gradient_clip: True